-- Criação dos esquemas para as camadas do ETL e visualizações

DROP SCHEMA IF EXISTS raw CASCADE;
CREATE SCHEMA raw;

DROP SCHEMA IF EXISTS staging CASCADE;
CREATE SCHEMA staging;

DROP SCHEMA IF EXISTS dm CASCADE;
CREATE SCHEMA dm;

DROP SCHEMA IF EXISTS analytics CASCADE;
CREATE SCHEMA analytics;
