-- Transformação de STAGING para DM

DROP TABLE IF EXISTS dm.saude_municipios CASCADE;

CREATE TABLE dm.saude_municipios AS
SELECT
    ROW_NUMBER() OVER (ORDER BY MUNICIPIO) AS ID_MUNICIPIO,
    MUNICIPIO,
    UF,
    REGIAO,
    POPULACAO,
    CASOS_COVID_2023,
    OBITOS_COVID_2023,
    PESSOAS_TESTADAS,
    TAXA_COBERTURA_VACINA,
    ROUND(CAST(CASOS_COVID_2023 AS NUMERIC) / POPULACAO * 100000, 2) AS TAXA_INCIDENCIA_COVID,
    ROUND(CAST(OBITOS_COVID_2023 AS NUMERIC) / CASOS_COVID_2023 * 100, 2) AS TAXA_MORTALIDADE_COVID,
    ROUND(CAST(PESSOAS_TESTADAS AS NUMERIC) / POPULACAO * 100, 2) AS PERCENTUAL_TESTADOS,
    CASE 
        WHEN TAXA_COBERTURA_VACINA >= 90 THEN 'Excelente'
        WHEN TAXA_COBERTURA_VACINA >= 80 THEN 'Bom'
        WHEN TAXA_COBERTURA_VACINA >= 70 THEN 'Regular'
        ELSE 'Crítico'
    END AS CLASSIFICACAO_VACINACAO,
    DATA_ATUALIZACAO,
    CURRENT_TIMESTAMP AS DATA_PROCESSAMENTO
FROM staging.saude_municipios
WHERE MUNICIPIO IS NOT NULL;

CREATE INDEX idx_dm_saude_municipio ON dm.saude_municipios(MUNICIPIO);
CREATE INDEX idx_dm_saude_uf ON dm.saude_municipios(UF);
CREATE INDEX idx_dm_saude_regiao ON dm.saude_municipios(REGIAO);
CREATE INDEX idx_dm_saude_classificacao ON dm.saude_municipios(CLASSIFICACAO_VACINACAO);
